language: node_js
node_js:
  - "12"
cache:
  directories:
    - node_modules
env:
  - CI=true
install:
  - npm install --registry=https://registry.npm.taobao.org
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist
  on:
    branch: main
